BankingSystem/Models/Base/BaseModel.cs
namespace BankingSystem.Models.Base
{
    public class BaseModel
    {
        public int Id { get; set; }
    }
}

BankingSystem/Models/Deposits/DepositModel.cs
using BankingSystem.Models.Base;

namespace BankingSystem.Models.Deposits
{
    public class DepositModel : BaseModel
    {
        public decimal Balance { get; set; }

        public DepositModel(decimal balance)
        {
            Balance = balance;
        }
    }
}

BankingSystem/Models/Loans/GuarantorModel.cs
using BankingSystem.Models.Base;

namespace BankingSystem.Models.Loans
{
    public class GuarantorModel : BaseModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        
        public string Phone { get; set; }
        public string Relationship { get; set; }

        public GuarantorModel(string firstName, string lastName, string phone, string relationship)
        {
            FirstName = firstName;
            LastName = lastName;
            Phone = phone;
            Relationship = relationship;
        }
    }
}

BankingSystem/Models/Loans/LoanModel.cs
using BankingSystem.Models.Base;
using System;

namespace BankingSystem.Models.Loans
{
    public class LoanModel : BaseModel
    {
        public decimal Amount { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime FinishDate { get; set; }

        public GuarantorModel Guarantor { get; set; }
        public LoanModel(decimal amount, DateTime startDate, DateTime finishDate)
        {
            Amount = amount;
            StartDate = startDate;
            FinishDate = finishDate;
        }
    }
}

BankingSystem/Models/Users/UserModel.cs
using System;
using BankingSystem.Models.Base;
using System.Collections.Generic;
using BankingSystem.Models.Loans;
using BankingSystem.Models.Deposits;

namespace BankingSystem.Models.Users
{
    public class UserModel : BaseModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public byte Gender { get; set; }

        public string UniqueNumber { get; set; }

        public DateTime BirthDay { get; private set; }

        public string Address { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public IList<LoanModel> Loans { get; set; }

        public IList<DepositModel> Deposits { get; set; }

        public string Branch { get; set; }

        public UserModel(int id, string firstName, string lastName, byte gender,
               string uniqueNumber, DateTime birthDay, string address,
               string email, string phone)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Gender = gender;
            UniqueNumber = uniqueNumber;
            BirthDay = birthDay;
            Address = address;
            Email = email;
            Phone = phone;
            Loans = new List<LoanModel>();
            Deposits = new List<DepositModel>();
        }
    }
}

BankingSystem/Controllers/DepositController.cs
using System.Web.Mvc;
using BankingSystem.Service;

namespace BankingSystem.Controllers
{
    [Authorize]
    public class DepositController : Controller
    {
        public static ExecutorServiceClient client;
        public DepositController()
        {
            client = new ExecutorServiceClient();
        }

        public ActionResult CreateDeposit(int id)
        {
            var model = new CreateDepositCommand()
            {
                UserId = id
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateDeposit(CreateDepositCommand command)
        {
            client.CreateDeposit(command);
            return View();
        }
    }
}

BankingSystem/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BankingSystem.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Main()
        {
            return View();
        }
    }
}

BankingSystem/Controllers/LoanController.cs
using System.Web.Mvc;
using BankingSystem.Service;

namespace BankingSystem.Controllers
{
    [Authorize]
    public class LoanController : Controller
    {
        public static ExecutorServiceClient client;
        public LoanController()
        {
            client = new ExecutorServiceClient();
        }

        public ActionResult CreateLoan(int id)
        {
            var model = new CreateLoanCommand()
            {
                UserId = id
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateLoan(CreateLoanCommand command)
        {
            client.CreateLoan(command);
            return View();
        }
    }
}

BankingSystem/Controllers/UserController.cs
using BankingSystem.Extensions;
using BankingSystem.Filters;
using BankingSystem.Service;
using PagedList;
using System;
using System.Web;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace BankingSystem.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public static ExecutorServiceClient client;
        public UserController()
        {
            client = new ExecutorServiceClient();
        }


        [AllowAnonymous]
        public ActionResult Login()
        {
            var model = new LoginUserCommand();
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginUserCommand command)
        {
            var client = new ExecutorServiceClient();
            var result = client.LoginUser(command);

            if (result != null)
            {
                var role = client.GetRoleName(result.Id);
                var ticket = new FormsAuthenticationTicket(1,result.Email,DateTime.Now, DateTime.Now.AddSeconds(525600), true, role);
                var encrypted = FormsAuthentication.Encrypt(ticket);
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                cookie.Expires = DateTime.Now.AddMinutes(525600);
                cookie.HttpOnly = true;
                Response.Cookies.Add(cookie);

                return RedirectToAction("Listing");
            }

            Session["CurrentUser"] = result;

            return RedirectToAction("Login");
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Login");
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            var model = new RegisterUserCommand();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(RegisterUserCommand command)
        {
            var result = client.CreateUser(command);

            return RedirectToAction("UserDetails", new UserDetailsQuery { Id = result.EntityId });
        }

        [PermissionProvider(RoleName = "Operator")]
        public ActionResult Update(int id)
        {
            var client = new ExecutorServiceClient();
            var user = client.QueryUserDetails(new UserDetailsQuery
            {
                Id = id
            });

            var model = user.MapToCommand();

            return View(model);
        }

        [HttpPost]
        [PermissionProvider(RoleName = "Operator")]
        public ActionResult Update(UpdateUserCommand command)
        {
            var result = client.UpdateUser(command);

            return RedirectToAction("UserDetails", new UserDetailsQuery { Id = result.EntityId });
        }

        [HttpPost]
        [PermissionProvider(RoleName = "Operator")]
        public ActionResult Delete(DeleteUserCommand command)
        {
            var result = client.DeleteUser(command);

            return RedirectToAction("UserDetails");
        }

        public ActionResult Details(UserDetailsQuery query)
        {
            var result = client.QueryUserDetails(query);
            var model = result.MapToModel();

            return View(model);
        }

        [PermissionProvider(RoleName = "Owner")]
        public ActionResult Listing(string firstName, string email, int? page)
        {
            var query = new UserListQuery()
            {
                FirstName = firstName,
                Email = email
            };
            var result = client.QueryUsers(query);
            var model = result.MapToModel().ToList().ToPagedList(page ?? 1, 3);

            return View(model);
        }
    }
}

BankingSystem/Views/Deposit/CreateDeposit.cshtml
@model BankingSystem.BankyngSystemService.CreateDepositCommand

@{
    ViewBag.Title = "CreateDeposit";
}

<h2>CreateDeposit</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateDepositCommand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthlyPay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthlyPay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthlyPay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankingSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BankingSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BankingSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BankingSystem/Views/Home/Main.cshtml
@{
    ViewBag.Title = "Main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

BankingSystem/Views/Loan/CreateLoan.cshtml
@model BankingSystem.Service.CreateLoanCommand

@{
    ViewBag.Title = "CreateLoan";
}

<h2>CreateLoan</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CreateLoanCommand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthlyPay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthlyPay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthlyPay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="checkbox" placeholder="თავმდები" id="check-guarantor">
        <div class="guarantor-tab" style="display:none">
            <div class="form-group">
                @Html.LabelFor(model => model.GuarantorFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GuarantorFirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GuarantorFirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.GuarantorLastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GuarantorLastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GuarantorLastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Relationship, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Relationship, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Relationship, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('#check-guarantor').change(function () {
            if (this.checked) {
                $('.guarantor-tab').fadeIn('slow');
            }
            else {
                $('.guarantor-tab').fadeOut('slow');
            }
        });
    </script>
}

BankingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("მეინ", "Main", "Home")</li>
                    <li>@Html.ActionLink("ჩვენს შესახებ", "About", "Home")</li>
                    <li>@Html.ActionLink("კონტაქტი", "Contact", "Home")</li>
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li><a href="">@HttpContext.Current.User.Identity.Name</a></li>
                        <li>@Html.ActionLink("მომხმარებლები", "Listing", "User")</li>
                        <li>@Html.ActionLink("გამოსვლა", "LogOut", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("შესვლა", "Login", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BankingSystem/Views/User/Details.cshtml
@model BankingSystem.Models.Users.UserModel

@{
    ViewBag.Title = "UserDetails";
}

<h2>UserDetails</h2>

<div>
    <h4>UserModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UniqueNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>
<p>
    <a href="@Url.Action("Update", new { id = Model.Id })">რედაქტირება</a>
    <a href="@Url.Action("CreateDeposit", "Deposit", new { id = Model.Id })">ანაბარის გახსნა</a>
    <a href="@Url.Action("CreateLoan", "Loan", new { id = Model.Id })">სესხის შევსება</a>
</p>

BankingSystem/Views/User/Listing.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BankingSystem.Models.Users.UserModel>

@{
    ViewBag.Title = "UsersListing";
}

<a href="@Url.Action("Register")">დამატება</a>
<h2>მომხმარებლები</h2>

@using (Html.BeginForm("UsersListing", "User", FormMethod.Get))
{
    @Html.TextBox("firstName", "", new { placeholder = "სახელი" })
    @Html.TextBox("email", "", new { placeholder = "იმეილი" })
    <input type="submit" value="Search" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().UniqueNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().BirthDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Phone)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniqueNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a href="@Url.Action("Details", new { id = item.Id })">დეტალები</a>
                <a href="@Url.Action("Update", new { id = item.Id })">რედაქტირება</a>
                <a href="@Url.Action("Delete", new { id = item.Id })">წაშლა</a>
            </td>
        </tr>
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("Listing", new { page, firstName = Request.QueryString["firstName"], lastName = Request.QueryString["email"] }), new PagedListRenderOptions { Display = PagedListDisplayMode.IfNeeded })

BankingSystem/Views/User/Login.cshtml
@model BankingSystem.Service.LoginUserCommand

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LoginUserCommand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankingSystem/Views/User/Register.cshtml
@model BankingSystem.Service.RegisterUserCommand

@{
    ViewBag.Title = "RegisterUser";
}

<h2>დაარეგისტრირეთ ფიზიკური პირი</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterUserCommand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BranchId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BranchId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UniqueNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UniqueNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UniqueNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}